version: "3"
services:
  database:
    image: "postgres:14"
    environment:
      - POSTGRES_USER=davehudson
      - POSTGRES_PASSWORD=the_dbpass
      - POSTGRES_DB=davehudson_db
    ports:
      - "5432:5432"
