version: "3"
services:
  database:
    image: "postgres:14"
    environment:
      - POSTGRES_USER=davehudson
      - POSTGRES_PASSWORD=the_dbpass
      - POSTGRES_DB=davehudson_db
    ports:
      - "5432:5432"
  app:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    volumes:
      - /app/node_modules
      - ./app:/apps/blog
    ports:
      - 3000:3000
