name: Fly Deploy Blog
on:
  push:
    branches:
      - main
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy blog app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@v1.4
        with:
          args: "deploy --config ./fly.toml --dockerfile ./Dockerfile"
